### ISSUE TITLE
python-nanonet_1.1.3-1_amd64.deb 404

### ISSUE THREAD

**Issue by vineeth-s** [nanoporetech/nanonet#25]
Hi,

I am trying to install nanonet with currennt  using the steps in TRAIN_INSTALL.md and get a 404 on this link - 

https://github.com/nanoporetech/nanonet/releases/download/v1.1.2/python-nanonet_1.1.3-1_amd64.deb

Also, with the ont-currennt, I am guessing there is a typo, the wget retrieves ont-currennt-0.2.1-3-trusty.deb but dpkg seems to want to install ont-currennt_0.2.1-2-trusty_amd64.deb 

What would be the current package names for these ?

Thanks much

**Comment by cjw85** [comment]
Hi @vineeth-s,

Apologies the TRAIN_INSTALL.md hasn't been updated for a while.

We do not currently have a deb package for recent nanonet versions; the project has evolved somewhat since they were written. It is recommended to install nanonet from the source following instructions in the main [README.md](https://github.com/nanoporetech/nanonet/blob/master/README.md#installation), since this is more flexible in the components that are build (and therefore the dependencies required).

The current currennt package can be downloaded from the [release](https://github.com/nanoporetech/currennt/releases) page. This package itself was built using the [Makefile](https://github.com/nanoporetech/currennt/blob/master/Makefile) in the source.

I hope this clarifies things for you.

**Comment by vineeth-s** [comment]
Thanks @cjw85
