### ISSUE TITLE
Nanonet performance issues

### ISSUE THREAD

**Issue by nmiculinic** [nanoporetech/nanonet#53]
I've installed latest nanonet commit (```pip2 install --user https://github.com/nanoporetech/nanonet/archive/bbd20d1531adab135c690aaca980f105b712f486.zip```) and now I'm base calling bunch fast5 reads.

However, GPU is heavily underutilized. It is 1-2s 100% utilization, and then 8s it's 0%. I've tried using multiple jobs but at most I see one process using the GPU, and that's it. During GPU downtime neither it's output file written to, nor do I see spiking CPUs on htop (It's Intel Xeon server, with 24 logical cores, more than enough to handle the load.)

```nanonetcall <dir> --platforms nvidia:0:1 --exc_opencl  --jobs 8 > output.fa```

**Comment by cjw85** [comment]
Hi @nmiculinic 

Benchmarks for nanonet are available within the readme: https://github.com/nanoporetech/nanonet#benchmarks. To improve GPU performance you should set the last component of the `--platforms` option to a larger number, this controls the number of concurrent kernels run by the OpenCL code (the `--jobs` option controls the number of python processes used for CPU multitasking).

I should say that nanonet is not optimised for speed; the CPU implementation is almost entirely numpy code. The GPU implementation involves quite a bit of back-and-forth between CPU and GPU. You may in fact find that fully utilising your Xeon cores by setting `--jobs 24` gives faster throughput than your GPU. Please see the notes in the README.md concerning use of threading.

For faster CPU performance we would recommend using the latest version of the Albacore basecaller which also implements newer, and more accurate, basecalling algorithms.

**Comment by nmiculinic** [comment]
I've tried a workaround by having multiple --platform nvidia:0:1 nvidia:0:1 ... instances,..it helps a bit thankfully

**Comment by cjw85** [comment]
As per the documentation and examples in the benchmarking section of the README.md, the intended use of the `--platforms` option is a list of OpenCL GPU platforms and devices to be used, in a format VENDOR:DEVICE:N_Files space separated, e.g.:

    --platforms nvidia:0:1 amd:0:2 amd:1:2

would use three OpenCL devices: the first nvidia device, and the first and second amd devices listed by `--list_platforms`. As you have it you will be processing a single file in multiple OpenCL contexts, rather than multiple files in a single context.

I will comment on your file writing problems on your dedicated issue.

**Comment by nmiculinic** [comment]
I've tried both ```--platforms nvidia:0:1 (*8)``` and ```--platforms nvidia:0:8```. 

It's not the same performance since I want to saturate GPU, and this ```--platforms nvidia:0:1  (*8)``` has higher average GPU utilization. Reason for that being 8 worker threads occupying GPU, and the CPU downtime isn't as big. 

If I used ``--platforms nvidia:0:8``` sure the GPU would longer be occupied, but I'd see 0% GPU utilization during CPU phase, which is 8 times longer now since I'm using 8 files.

**Comment by cjw85** [comment]
As far as I understand multiple OpenCL contexts on a device cannot execute tasks simultaneously, so its not typically advisable to start multiple contexts for a single device. I would be sure to benchmark the execution time of nanonetcall rather than simply looking at GPU utilisation.

As I said above, performance is not really a goal of nanonet (and it has certainly been superseded by Albacore for CPU performance) so I'm going to close this issue. That's not to say that we don't welcome PRs if they make the code faster without unduly complicating it.
